# Site settings
title: Root Inc. Dev
description: > # this means to ignore newlines until "baseurl:"
  Learnings and musings from the development team at Root Inc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rootinc.github.io" # the base hostname & protocol for your site
permalink: /:year/:month/:day/:title/
twitter_username: rootincdev
github_username:  rootinc

# Build settings
markdown: kramdown
